### ISSUE TITLE
Finish milestone 1 deliverable

### ISSUE THREAD

**Issue by AugmenTab** [albuquirky/albuquirky.github.io#1]
* [ ] Review entity classes
* [ ] Create data model implementation page w/ links to entity classes
* [ ] Review ERD 
* [ ] Update exported ERD files
